### ISSUE TITLE
Instagram sharing sometimes crashes

### ISSUE THREAD

**Issue by fransyozef** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#513]
I'm using the cordova Instagram plugin .. sometimes it works .. but sometimes it quits and I get the following error:

2016-01-26 12:44:27.150 myapp[13566:5763386] *** Assertion failure in -[_UIOpenWithAppActivity performActivity], /BuildRoot/Library/Caches/com.apple.xbs/Sources/UIKit/UIKit-3512.30.14/UIDocumentInteractionController.m:408
2016-01-26 12:44:27.156 myapp 0x1821f899c 0x186bfefb0 0x186e29970 0x1868cfc90 0x1868d2e88 0x1866a7284 0x1865b3394 0x1865b2e90 0x1865b2d18 0x183f89c00 0x1002d5bb0 0x1002db658 0x18183cbb0 0x18183aa18 0x181769680 0x182c78088 0x1865e0d90 0x10007d2d0 0x18130a8b8)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb)

also this error, I think it's similar

2016-01-27 00:13:48.079 myapp[14240:5915310] *** Assertion failure in -[_UIOpenWithAppActivity performActivity], /BuildRoot/Library/Caches/com.apple.xbs/Sources/UIKit/UIKit-3512.30.14/UIDocumentInteractionController.m:408
2016-01-27 00:13:48.086 myapp[14240:5915310] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'UIDocumentInteractionController has gone away prematurely!'
*** First throw call stack:
(0x181885900 0x180ef3f80 0x1818857d0 0x1821f899c 0x186bfefb0 0x186e29970 0x1868cfc90 0x1868d2e88 0x1866a7284 0x1865b3394 0x1865b2e90 0x1865b2d18 0x183f89c00 0x1002a1bb0 0x1002a7658 0x18183cbb0 0x18183aa18 0x181769680 0x182c78088 0x1865e0d90 0x1000452d0 0x18130a8b8)
libc++abi.dylib: terminating with uncaught exception of type NSException

I'm using the plugin with Ionic

Some info:

Cordova CLI: 5.4.1
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.0
Ionic CLI Version: 1.7.13
Ionic App Lib Version: 0.6.5
ios-deploy version: 1.8.3 
ios-sim version: 5.0.4 
OS: Mac OS X El Capitan
Node Version: v4.2.2
Xcode version: Xcode 7.2 Build version 7C68

see forum post : https://forum.ionicframework.com/t/instagram-sharing-fails/42089

I sometimes have the same with Whatsapp

**Comment by EddyVerbruggen** [comment]
Thanks for the details but I'm unable to reproduce this behavior. I totally believe it happens and you're not the only one with this issue, but it's impossible for me to create a fix if I can't reproduce it.

I did however just push a little change to the problematic property, so if you update the master branch please let me know if it makes any difference.

**Comment by ericappcomm** [comment]
I've got the problem that Instagram crashes using the social-sharing plugin.
It opens airdrop. And when clicking Instagram it crashes and my app is closed.
When opening airdrop and before clicking the Instagram icon, I see a warning in the xcode-log:

Warning: Attempt to present <_UIDocumentActivityViewController: 0x18f93ee0>  on <MainViewController: 0x17569790> which is already presenting <_UIDocumentActivityViewController: 0x1c83a400>

It does NOT crashes when I open airdrop (via the plugin),  first click cancel and then open it again. Also the warning does not appear the second attempt.

What can be de case of this strange thing?
(I does not have any problems on iPhone 6Plus)

iOS 9.2
plugin 5.0.10

**Comment by ElodieC** [comment]
I'm having the same issue but it is systematic. It happens with : plugin 5.0.10 and iOS 9.2 with iphone 4s

**Comment by EddyVerbruggen** [comment]
@ElodieC I will if you can share your project with me so I can try to reproduce it once more.

The original report seems to be about the Instagram plugin btw, that's not this one.

**Comment by ElodieC** [comment]
I don't manage to reproduce it with a sample app and I can't share the code of the whole app with you. This is the stack trace that I got :  
```
2016-03-07 13:58:55.121 myapp[674:119853] Warning: Attempt to present <_UIDocumentActivityViewController: 0x162c9e00>  on <MainViewController: 0x15d80350> which is already presenting <_UIDocumentActivityViewController: 0x16acb000>
2016-03-07 13:58:58.210 myapp[674:119853] *** Assertion failure in -[_UIOpenWithAppActivity performActivity], /BuildRoot/Library/Caches/com.apple.xbs/Sources/UIKit/UIKit-3512.30.14/UIDocumentInteractionController.m:408
2016-03-07 13:58:58.212 myapp[674:119853] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'UIDocumentInteractionController has gone away prematurely!'
*** First throw call stack:
(0x20a4010b 0x201e6e17 0x20a3ffe1 0x21213b19 0x251d0379 0x253d7a5f 0x24ec4a93 0x24ec7d35 0x24ca909f 0x24bb7b25 0x24bb7605 0x24bb74ff 0x22c7ea21 0x40bc83 0x41076d 0x20a033fd 0x20a018f7 0x20954bf9 0x209549e5 0x21ba0ac9 0x24be4ba1 0xce2d3 0x20603873)
libc++abi.dylib: terminating with uncaught exception of type NSException
```

And this is a sample project using the same method but not failing : 
https://github.com/ElodieC/bugShareInstagram

**Comment by EddyVerbruggen** [comment]
So you're saying the problem is in your code then?

**Comment by ElodieC** [comment]
This was due to a click fired two times on the button. I've fixed it. Maybe, something should be done with the plugin to avoid crashing when this happens.

**Comment by EddyVerbruggen** [comment]
No I'm sorry, that's not up to the plugin.

**Comment by zh-wowtv** [comment]
This problem still exists. But it only happened the first time when I installed the application. My version is 5.1.3.

**Comment by jasenhuang** [comment]
i meet the same problem and fix it already.
all you need to do is  hold UIDocumentInteractionController on somewhere
